gitRepository:
  spec:
    interval: 5m
    url: https://github.com/woodenmaiden/simaris.git
    ref:
      branch: main
    secretRef:
      name: git-credentials
kustomization:
  spec:
    interval: 5m
    prune: true
    wait: true

# Delete the following lines when the cluster isn't single node anymore

cli:
  tolerations:
  - key: "node-role.kubernetes.io/master"
    operator: "Exists"
    effect: "NoSchedule"
