gitRepository:
  spec:
    interval: 5m
    url: https://github.com/woodenmaiden/simaris.git
    ref:
      branch: main
    secretRef:
      name: git-credentials
kustomization:
  spec:
    interval: 5m
    prune: true
    wait: true
